version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install --force

  build:
    commands:
      #- npm run start
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # This will include all files in the build directory
  discard-paths: yes  # This will discard the directory structure in the artifact
